scraper:
  scraperSites:
    -
      name: amazon.de
      url: https://www.amazon.de/dp/%s
      scraperSiteType: AMAZONDE
    -
      name: amazon.fr
      url: https://www.amazon.fr/dp/%s
      scraperSiteType: AMAZONFR
    -
      name: bricklink.com
      url: https://www.bricklink.com/ajax/clone/catalogifs.ajax?itemid=%s&ss=BE&cond=N&ii=0&iconly=0
      scraperSiteType: BRICKLINK

  itemsToWatch:
    -
      name: Knight's Cycle polybag
      sites:
        -
          id: B01BB7470E
          scraperSiteType: AMAZONDE
        -
          id: 140552
          scraperSiteType: BRICKLINK
        -
          id: B01BB7470E
          scraperSiteType: AMAZONFR
    -
      name: Wish Fountain polybag
      sites:
        -
          id: B00W3SV87Q
          scraperSiteType: AMAZONDE
        -
          id: B00W3SV87Q
          scraperSiteType: AMAZONFR
        -
          id: 132247
          scraperSiteType: BRICKLINK
    -
      name: Volkswagen T1 Camper
      sites:
        -
          id: B0050R0XEG
          scraperSiteType: AMAZONDE
        -
          id: B0050R0XEG
          scraperSiteType: AMAZONFR
        -
          id: 102314
          scraperSiteType: BRICKLINK
    -
      name: Display Team Jet
      sites:
        -
          id: 140073
          scraperSiteType: BRICKLINK
        -
          id: B012NOF7VC
          scraperSiteType: AMAZONDE
        -
          id: B012NOF7VC
          scraperSiteType: AMAZONFR
    -
      name: Scarif Stormtrooper polybag
      sites:
        -
          id: 155767
          scraperSiteType: BRICKLINK
        -
          id: B0753ZQ81F
          scraperSiteType: AMAZONDE
        -
          id: B0753ZQ81F
          scraperSiteType: AMAZONFR
    -
      name: Mighty Dinosaurs
      sites:
        -
          id: 150086
          scraperSiteType: BRICKLINK
        -
          id: B01J41DNWM
          scraperSiteType: AMAZONDE
        -
          id: B01J41DNWM
          scraperSiteType: AMAZONFR
    -
      name: Azari & the Goblin Forest Escape
      sites:
        -
          id: B06WLL3T2Q
          scraperSiteType: AMAZONDE
        -
          id: B06WLL3T2Q
          scraperSiteType: AMAZONFR
        -
          id: 155347
          scraperSiteType: BRICKLINK
    -
      name: Ship in a Bottle
      sites:
        -
          id: B079PDGK55
          scraperSiteType: AMAZONFR
        -
          id: B079PDGK55
          scraperSiteType: AMAZONDE
        -
          id: 161375
          scraperSiteType: BRICKLINK
    -
      name: Lunar Lander
      sites:
        -
          id: B07G3WS3KV
          scraperSiteType: AMAZONFR
        -
          id: B07G3WS3KV
          scraperSiteType: AMAZONDE
        -
          id: 176605
          scraperSiteType: BRICKLINK
    -
      name: Train 40 Years
      sites:
        -
          id: 185524
          scraperSiteType: BRICKLINK
        -
          id: B085DXZWRF
          scraperSiteType: AMAZONDE
        -
          id: B085DXZWRF
          scraperSiteType: AMAZONFR
    -
      name: Stormtrooper Helmet
      sites:
        -
          id: B07XFXWK48
          scraperSiteType: AMAZONFR
        -
          id: B07XFXWK48
          scraperSiteType: AMAZONDE
        -
          id: 180997
          scraperSiteType: BRICKLINK
    -
      name: Boba Fett Helmet
      sites:
        -
          id: B07XFXZ4B7
          scraperSiteType: AMAZONFR
        -
          id: B07XFXZ4B7
          scraperSiteType: AMAZONDE
        -
          id: 181000
          scraperSiteType: BRICKLINK


